### ISSUE TITLE
GitHub icon on the website is unreasonably large until JS loads

### ISSUE THREAD

**Issue by chris-morgan** [WICG/open-ui#10]
I have JS disabled by default, but this tends to cause a long flash of misstyled content too, so normal users are affected by this too.

The GitHub logo that’s supposed to appear in the top right hand corner lacks a width and height, having only a viewBox specified. And the CSS doesn’t fix this. The result of it is that the logo fills the available width until some JS loads and executes, inserting a few styles, including this critical one:

```css
.svg-inline--fa.fa-w-16 {
    width: 1em;
}
```

In order to fix this, add `width="1em"` to the `<svg>` element.

Nothing else is obviously using fa. I opine that its JS should be dropped. It’s terrible for user experience.

Then I suggest dropping the “This app works best with JavaScript enabled.” message. This is a *website*, and nothing critical looks to use JS. The component matrix sort button uses it, but that button should just be removed unless JS is enabled.

**Comment by levithomason** [comment]
@chris-morgan, thanks for the note. Indeed, there is an ugly FOUT issue.  Contributions simplifying the icons are much welcome!

FWIW, the site is built with Gatsby which uses React with SSR for building static pages and also for dynamic content.  One dynamic example is the component table you already pointed out.  This table has a lot more features planned so it will need to remain JS.

The site itself is likely to continue adding some JS powered features so we'll stay on Gatsby for now.  Again, any contributions simplifying things are always welcome.  Cheers!

**Comment by chris-morgan** [comment]
Did you intend to close this?

**Comment by pepelsbey** [comment]
It’s still an issue: while loading in Firefox the whole page jumps from this to the normal:

![Screenshot_2020-06-16 https open-ui org](https://user-images.githubusercontent.com/105274/84761008-7e499a80-afd1-11ea-95f2-bc444b6744a2.png)

I’m not sure why would you close this issue instead of fixing it.

**Comment by pepelsbey** [comment]
I’ll be glad to fix it (it’s pretty minor fix) if you can point me to the source code.
