### ISSUE TITLE
Concepts component should collapse and expand the examples

### ISSUE THREAD

**Issue by gregwhitworth** [WICG/open-ui#118]
While the concepts section is useful, it can make scrolling really long on large components and make navigating the page a chore. I have a recommendations to remedy this.

* Make it so that the labels toggle the visibility of the concepts from the different libraries.

A good example of where this would be helpful is on the [datepicker](https://open-ui.org/components/datepicker.research) research page.

The research is great but it's hard to see where one concept starts and another ends.

**Comment by gregwhitworth** [comment]
@assuncaocharles any chance you might be able to take a look at fixing this? You seem pretty knowledgeable with react.

**Comment by assuncaocharles** [comment]
@gregwhitworth Fixed, PR linked
