### ISSUE TITLE
Pages on https://open-ui.org/ are missing titles

### ISSUE THREAD

**Issue by dfabulich** [WICG/open-ui#120]
View source on https://open-ui.org/

Actual: `<title data-react-helmet="true"></title>`
Expected: `<title data-react-helmet="true">Open UI</title>`

All of the pages on the Open UI website seem to have this problem.

**Comment by gregwhitworth** [comment]
I've pushed a commit for this but for some reason it's not showing up, hopefully @levithomason can shed some light on this but it will get addressed shortly.

**Comment by gregwhitworth** [comment]
This is completed.
