### ISSUE TITLE
Make <select> change to closed state when focus leaves listbox

### ISSUE THREAD

**Issue by dandclark** [WICG/open-ui#137]
Today I set out to make what I thought would be a simple improvement: update the `<select>` anatomy such that the `listbox` part has a `blur` event handler that switches the `open` state to `false`.  This achieves the classic `<select>` behavior where clicking outside the listbox (or anything else that causes focus to jump elsewhere on the page) causes it the listbox to be collapsed.

It turns out that `blur` doesn't quite work; it doesn't bubble, so when focus goes from an option in the listbox to something else, the listbox won't get the event.  Note: the listbox itself normally isn't focusable, only its contents.

An better alternative is `focusout`.  This one fires when anything in the subtree of the element loses focus.  This is a bit too noisy by default, since it will fire when focus switches from one `<option>` to another, but we can scope it thusly (`relatedTarget` for focusout is the element that is receiving focus):
```js
if (!event.relatedTarget || // event.relatedTarget is null if something non-focusable was clicked and focus is going back to the <body>
    !listbox.contains(event.relatedTarget)) { // Close the <select> if the focus target isn't in the listbox's subtree.
// set <select> `open` state to false
}
```
This mostly works except for the case when something non-focusable is clicked inside the listbox.  In the context of `focusout` this is indistinguishable from when something non-focusable is clicked outside the listbox (`relatedTarget == null` either way).  So, it will cause the `<select>` to close, which seems wrong.  Non-focusable things would include `<optgroup>` headers and dividers like the one in [Bootstrap buttons](https://getbootstrap.com/docs/4.0/components/dropdowns/#split-button-dropdowns) (the spacer between Option Three and Option 4):

![image](https://user-images.githubusercontent.com/1688716/87999274-23fb9800-caaf-11ea-90fb-121f4b9ecbe3.png)

For the native `<select>`, clicking an `<optgroup>` caption does not cause the `<select>` to close in at least Chrome/Edge/Firefox.  This matches my expectation.  With Bootstrap buttons, clicking the divider actually *does* cause it to collapse, which is not what I would expect and might actually be due to the implementation difficulties that I'm outlining.

So, how to denote this behavior in the `<select>` anatomy?  I was hoping that we could continue to express behavior in terms of JS event handlers, but I'm not sure that is possible here without invoking hacks such as using e.g. `mouseover`/`mouseout` or watching `click` event bubbling in the listbox to alter the behavior of the `focusout` handler somehow such that it won't trigger a close for clicks inside the popup.

Thoughts? @gregwhitworth @melanierichards Native light-dismiss for the listbox popup should make all this "just work", but there is still the question of how to describe this behavior in the `<select>` anatomy tables if this is not straightforwardly possible to implement in terms of JS events.

Or maybe it's fine to just collapse the `<select>` when something non-focusable inside the listbox is clicked.  It doesn't seem to be a blocker for Bootstrap.

Or maybe (hopefully) I'm missing a more straightforward way to achieve this behavior. :)

**Comment by melanierichards** [comment]
Interesting, thanks for doing this investigation, Dan! Like you I'm not sure if there's any non-hacky way to tie this all together, so it may be the case that this is indeed not trivially achievable by an author, who must combine events to approach parity with the native behavior.

There's probably some kind of boiler plate language we can come up with for instances such as these, e.g. "Native light-dismiss behavior not trivially expressed in script". Is there somewhere you think we should describe this behavior other than expanding on what we have in "Behavior" > "Interaction & transition of states" > "Open State"?

> Or maybe it's fine to just collapse the `<select>` when something non-focusable inside the listbox is clicked. It doesn't seem to be a blocker for Bootstrap.

I think it would be better to consider this a blocker for Open UI, as a matter of accessibility w/r/t mobility (e.g. someone intended to click on a focusable descendent and missed the target).

**Comment by gregwhitworth** [comment]
> I think it would be better to consider this a blocker for Open UI, as a matter of accessibility w/r/t mobility (e.g. someone intended to click on a focusable descendent and missed the target)

I think this issue should be two fold:

1. Should the `select` change the `open` state when a non-focusable element is invoked in the `list-box` subtree?
2. If it's a 'no' for number 1, then how do we express this?

> Native light-dismiss for the listbox popup should make all this "just work", but there is still the question of how to describe this behavior in the <select> anatomy tables if this is not straightforwardly possible to implement in terms of JS events.

My proposal for item 2 would be to give this a name (`light dismiss` seems a fine strawman to me) and then define in the select spec. This will allow you to denote it simply as other JS events but link to the full definition which will probably have numerous events and how to collect the elements in the subtree of listbox. 

As we know, many different specifications will take advantage of behavior definitions of popups so it may be worth having a page devoted to popups (shocker, I know 😃). Until that time comes however, we can start the definition in select.

**Comment by gregwhitworth** [comment]
> I think it would be better to consider this a blocker for Open UI, as a matter of accessibility w/r/t mobility (e.g. someone intended to click on a focusable descendent and missed the target)

I think this issue should be two fold:

1. Should the `select` change the `open` state when a non-focusable element is invoked in the `list-box` subtree?
2. If it's a 'no' for number 1, then how do we express this?

> Native light-dismiss for the listbox popup should make all this "just work", but there is still the question of how to describe this behavior in the `<select>` anatomy tables if this is not straightforwardly possible to implement terms of JS events.

My proposal for item 2 would be to give this a name (`light dismiss` seems a fine strawman to me) and then define in the Open UI `select` spec. This will allow you to denote it simply as other JS events but link to the full definition which will probably have numerous events and how to collect the elements in the subtree of listbox. 

As we know, many different specifications will take advantage of behavior definitions of popups so it may be worth having a page devoted to popups (shocker, I know 😃). Until that time comes however, we can start the definition in select.

**Comment by melanierichards** [comment]
> My proposal for item 2 would be to give this a name (light dismiss seems a fine strawman to me) and then define in the Open UI select spec. This will allow you to denote it simply as other JS events but link to the full definition which will probably have numerous events and how to collect the elements in the subtree of listbox.

+1 to this proposal!

> so it may be worth having a page devoted to popups

I think this makes sense, hopefully we can use the in-progress popup research page as a jumping off point for this :)

**Comment by dandclark** [comment]
Thanks to both of you, I agree with this approach.
I'll create a PR to refactor the "light dismiss" behavior into its own section that we can either iterate on eventually change to reference the popup documentation when it's ready.

**Comment by gregwhitworth** [comment]
@dandclark out of curiosity is there a need for a `blur` type event that bubbles? Should we possibly propose one to WHATWG?

**Comment by dandclark** [comment]
That would be roughly the same thing as `focusout`.  The problem is that for both `blur` and `focusout`, when something non-focusable is clicked, there's no way to tell *what* non-focusable element was clicked, because the `event.relatedTarget` is always null and the `document.activeElement` always goes to the body.  So we can't easily distinguish whether the click was inside or outside of the listbox.

I'm not sure yet what platform primitive I would propose here.  Introducing light dismiss into the platform more formally through a `<dialog>`/`<popup>` element would perhaps be enough, and that's something that's being worked on.

Other ideas could be to include the target of the click on the Event object, or establish some context where focus doesn't always fall back to the `<body>` but can fall back to some specified ancestor element if a non-focusable descendant is clicked.
