### ISSUE TITLE
Should the Home and End keys jump to the first and last <option>?

### ISSUE THREAD

**Issue by dandclark** [WICG/open-ui#154]
We should consider making the Home/End keys jump to the beginning/end of the `<select>`'s options list.
Works in Chromium, Firefox, and Safari `<select>`s.  Doesn't work in [bootstrap](https://getbootstrap.com/docs/4.3/components/dropdowns/#split-button) or [ant design](https://ant.design/components/select/), but perhaps it should.

**Comment by chrisdholt** [comment]
I think this is a limitation of those libraries and we should drive towards any existing standards or specs from an interaction model standpoint.
