### ISSUE TITLE
Should proposals include details of current workarounds?

### ISSUE THREAD

**Issue by mrmckeb** [WICG/open-ui#175]
When working on the proposal for the File input (#140), I added details around how developers currently implement custom file inputs.

Should this be a part of the proposal? If so, should this be detailed with a code example, or just a summary?

**Comment by gregwhitworth** [comment]
This was discussed in the last telecon and it was resolved to take it on a case-by-case basis. Minutes are here: https://www.w3.org/2020/09/24-openui-minutes.html

Due to this resolution I'm going to close this issue as the feedback specific to the file proposal should be handled in the PR.
