### ISSUE TITLE
Switch component page issues

### ISSUE THREAD

**Issue by kant2002** [WICG/open-ui#186]
I look at the https://open-ui.org/components/switch page and found many elements which was missing. I attempt to review what's missing and most of them can be removed.

1. Label concept non-existing on the AtlassKit. They are separate component. See https://atlassian.design/components/toggle/examples
2. Save for value and name concepts in AtlassKit. 
3. Image concept in Evergreen non-existing. 
4. Value, Name, Id, Height concepts maybe exists in Evergreen, but this is does not make sense to me, since this is mostly data properties which does not affect appearance.
5. Theme and appearance concepts do exists in Evergreen, but they canot be expressed in design system. There properties ortogonal to the goal of this project in my opinion.
6. HasCheckIcon concept in Evergreen present, and may be image for it should be produced.

I can do removal in https://github.com/WICG/open-ui/blob/master/research/src/sources/atlassian.json5 and https://github.com/WICG/open-ui/blob/master/research/src/sources/evergreen.json5 if needed.

**Comment by kant2002** [comment]
@una Do you the right person to ask for review these issues?

**Comment by gregwhitworth** [comment]
Hey @kant2002 any chance you can make a PR of your changes? Since switch is an analysis page it's a collection of examples. We welcome any additions/modifications that you may be able to provide. Let me know if you have any questions.
