### ISSUE TITLE
Tabs: Provide better description

### ISSUE THREAD

**Issue by bkardell** [WICG/open-ui#192]
The text in the current PR:

> *Tabs* are a set of sections of content that display one panel of content at a time. Each tab panel has an associated tab element, that when activated, displays the panel. The list of tab elements is arranged along one edge of the currently displayed panel.

I would say that from looking across 30 years worth of some different design systems we could be more specific about where they seem to agree, and link too.. 

> *Tabs* are a widget* which provides [well-defined meaning and interaction](https://www.w3.org/TR/wai-aria-practices/#tabpanel) allowing one-at-a-time, non-sequential viewing over a  series of thematically grouped, state independent and labelled sections.  They merely increase the users ability to understand and consume these bits of content.  

As far as 'along one edge' - I get it, and I'm not opposed to keeping it but I will just add that these guides once upon a time said said 'at the top'.  That wasn't really debatable.  Then came "well... or on the left".  With mobile devices, on the bottom actually became quite common as well and... I guess some are on the right too?  As hard as it is to imagine, I didn't really image those other things either, and I have seen plenty of responsive tabs that collapse these to inline to something that a lot of designers would call an 'accordion' but actually in every other way are just 'vertical tabs' (accordions in most systems/ARIA can have a multi-open nature like a series of summary/details), including key-handling and roles, really.  Single view with label and keyboard accessibility is also basically what describes a decent '[tabbed carousel](https://www.w3.org/TR/wai-aria-practices/#tabbed-carousel-elements)', I guess - which, also, you know, doesn't probably _look_ like tabs at all in a way... But I guess we need to work to where we draw the lines so I will refer back to this issue because it's hard to untangle these into which section of the document wags which other

* HTML/ARIA term of art.

**Comment by chrisdholt** [comment]
I'm not sure if the second quote is a proposal, but I would welcome that as a replacement for what is in the current spec. I'd agree that by avoiding semantics related to the visual markup we can better encapsulate things like the "tabbed carousel".

**Comment by gregwhitworth** [comment]
@bkardell @chrisdholt who wants to do the PR for this then?

**Comment by una** [comment]
Gentle bump on a PR for this :)
