### ISSUE TITLE
I would add Tab Labels would also flip (i.e. icons next to a label)

### ISSUE THREAD

**Issue by gregwhitworth** [WICG/open-ui#194]
I would add Tab Labels would also flip (i.e. icons next to a label)

_Originally posted by @una in https://github.com/WICG/open-ui/pull/183#discussion_r501291718_

**Comment by gregwhitworth** [comment]
Here is what @matthewp stated following:

> Can you provide some text you'd like to see here? I'm not exactly sure what you mean but happy to add it.

So the ball is in your court @una

**Comment by una** [comment]
I don't even remember what I meant by this 😂

**Comment by gregwhitworth** [comment]
@una I think you're referring to internationalization that not only should tab ordering adjust but also icons, etc.
