### ISSUE TITLE
Provide a slot for unchecked checkbox

### ISSUE THREAD

**Issue by brandonferrua** [WICG/open-ui#199]
After reviewing https://open-ui.org/components/checkbox, I'd like to propose a change to the anatomy of the checkbox to accommodate the unchecked state of a checkbox.

Based on what is there now, it is assumed that the control only allows for part targeting of two states of a checkbox:

1. Checked
2. Indeterminate

If you consider the binary or ternary, due to the indeterminate state, semantics of a checkbox then I think it only makes sense to have a `slot` to accommodate the unchecked state.

The unchecked rendering of a checkbox is typically the bounding "box" with no "indicator" visible. Let's say I have a scenario where I want to enable a user to "add" or "remove" an option from a list, wanting to retain the semantics of checkbox, I'd like to have my "unchecked" state render as a `+` symbol to inform the user that they are "adding" an option to my form.

Currently, the anatomy does not accommodate this scenario. This is partly due to the naming of the "checked-indicator" `part` attribute and name of the `slot` since it is only capturing the "checked" state.

I see two potential modifications to the current anatomy being proposed:

1. Rename the `part` and `name` of the checked state to just `indicator`

```html
<host>
  <label part="label"><slot name="label"></slot></label>
  <div part="control">
    <div part="indicator">
      <slot name="indicator"></slot>
    </div>
    <div part="indeterminate-indicator">
      <slot name="indeterminate-indicator"></slot>
    </div>
  </div>
</host>
```

Where the `slot` fallback can be the "unchecked" state.

2. Add a new element and slot to manage the unchecked state of the checkbox. Dropping `indicator` since it becomes redundant as all the elements inside the control manage each "state" of the control.

```html
<host>
  <label part="label"><slot name="label"></slot></label>
  <div part="control">
    <div part="unchecked">
      <slot name="unchecked"></slot>
    </div>
    <div part="checked">
      <slot name="checked"></slot>
    </div>
    <div part="indeterminate">
      <slot name="indeterminate"></slot>
    </div>
  </div>
</host>
```

**Comment by gregwhitworth** [comment]
@chrisdholt @nicholasrice ^

**Comment by gregwhitworth** [comment]
Here is the [resolution](https://www.w3.org/2020/10/22-openui-minutes.html) from today's telecon:

> RESOLUTION: Adjust the checkbox anatomy to have a single indicator that will be changed upon state change for checked, indeterminate, unchecked

@chrisdholt and @nicholasrice can you please provide your input. This would adjust the anatomy to this:

```
<host>
  <label part="label"><slot name="label"></slot></label>
  <div part="control">
    <div part="indicator">
           <slot></slot>
    </div>
  </div>
</host>
```

**Comment by brandonferrua** [comment]
For additional context, Salesforce's design system has this unique scenario to be solved where we want a checkbox to look like a button (https://www.lightningdesignsystem.com/components/checkbox-button/). This variant aims to solve the scenario I attempted to describe in the original post (https://www.lightningdesignsystem.com/components/list-builder/)

**Comment by nicholasrice** [comment]
I missed the call but I think this is a good modification!

**Comment by chrisdholt** [comment]
@gregwhitworth I think this is a better path forward. Thanks for driving this ahead on the call.
