### ISSUE TITLE
Improve alt text for images in Analysis pages

### ISSUE THREAD

**Issue by davidluhr** [WICG/open-ui#208]
## Issue

It appears that the alt text for example images on the analysis pages is generated from a template, as they follow the same pattern.

Here's a sample: "An image of the basic concept on a Breadcrumb component in Ant Design."

"basic", "Breadcrumb", and "Ant Design" seem to be the dynamic pieces of data to construct the alt text.

## Suggestion

This could be improve by removing "An image of", as this is redundant for assistive technology, where the image element's role will be announced.

Additionally, it seems that "concept on a" has a typo and should read "concept of a".

**Comment by kant2002** [comment]
I think this can be closed

**Comment by davidluhr** [comment]
Thanks for the improvement! I'll close this on my end since your PR was merged.
