### ISSUE TITLE
Clarification on `discipline`

### ISSUE THREAD

**Issue by GarthDB** [WICG/open-ui#22]
There are a few design system JSON files that use `"discipline": "development"`. I was looking to see what other options were available and didn't find it documented.

Additionally, as I'm filling out the Spectrum data, we have separate URLs for the design system usage guidelines and CSS implementation. When we add JS implementations we will have additional URLs for those. Is this something that is supported or will be supported?

**Comment by gregwhitworth** [comment]
@levithomason can you help clarify this?

**Comment by levithomason** [comment]
Thanks for the comment.  Have a look at #35.

Our original goal was to know where the jargon was originating from, such as from development (engineering) or from design.  The location and use of the field probably needs more work to be useful.  Comments and ideas welcome!

**Comment by levithomason** [comment]
>Additionally, as I'm filling out the Spectrum data, we have separate URLs for the design system usage guidelines and CSS implementation. When we add JS implementations we will have additional URLs for those. Is this something that is supported or will be supported?

Yes and yes.  I think we need a discipline field perhaps at the concept or component level opposed to the design system level itself.  Most design systems encompass both design/development terminology.  When we record the terms, that might be the right place to record the discipline it originated from.

Thoughts?
