### ISSUE TITLE
Mobile design

### ISSUE THREAD

**Issue by kant2002** [WICG/open-ui#220]
I think is funny that website dedicated to bring good UI has subpar website on mobile

![image](https://user-images.githubusercontent.com/4257079/99889909-f81e3800-2c83-11eb-8f85-b857e60f4c63.png)

Any ideas how to improve?

**Comment by kant2002** [comment]
Seems to be duplicate of https://github.com/WICG/open-ui/issues/170

**Comment by brianespinosa** [comment]
And should be addressed in #29
