### ISSUE TITLE
Enhancement: Need to show popper on table cells whose text gets hidden due to cell width being too short 

### ISSUE THREAD

**Issue by karunkamal** [WICG/open-ui#23]
table cells show dont show the component name properly 

proposing solution add title attribute and display something like this. (or use popper) 
<img width="950" alt="Screenshot 2019-11-15 at 11 04 42 AM" src="https://user-images.githubusercontent.com/13069255/68935239-4e79b080-07be-11ea-942d-c0310b5cb63c.png">

**Comment by gregwhitworth** [comment]
@assuncaocharles any chance you might be able to tackle this one?

**Comment by assuncaocharles** [comment]
@gregwhitworth I will have a look

**Comment by assuncaocharles** [comment]
@gregwhitworth fixed and linked PR
