### ISSUE TITLE
Tabs: Lazyload

### ISSUE THREAD

**Issue by ayumi-cloud** [WICG/open-ui#238]
Something we have done in our cms, was adding `lazyloading` to **tabs**, which increased performance for all themes and plugins.

It would be kind of nice if that was rolled out to tabs in a web standardized form.

**Comment by ayumi-cloud** [comment]
Closing this and adding it to the tabs discussion issue.

**Comment by mrmckeb** [comment]
Thanks for sharing, @ayumi-cloud.

I can see lazy-loading being applied to the contents of many components - perhaps there should be a lazy-loading component itself, which could be the child of tabs (and other elements)?

Can you explain more how you would expect this to work? How would a developer make use of this feature?

**Comment by ayumi-cloud** [comment]
> Can you explain more how you would expect this to work? How would a developer make use of this feature?

Sure, I was hoping that developers could have `Native lazyloading for tabs` and use the same methods that Addy Osmani from Google used to natively lazy load images in browsers, see here: https://addyosmani.com/blog/lazy-loading/

To lazy load tabs, developers could just add an attribute to the tabs, see [lazyloading attributes](https://html.spec.whatwg.org/#lazy-loading-attributes)

The original Lazyloading explainer can be found here: https://github.com/scott-little/lazyload

Hope that helps.

p.s. Would be interested to know what other components you are thinking to lazyload.

**Comment by Malvoz** [comment]
@ayumi-cloud where does the content in the tabs come from? During the finalization of the `loading` attribute for `img` someone asked about potentially enabling lazy-loading for custom components, see discussion from https://github.com/whatwg/html/pull/3752#issuecomment-504060118 (you'll probably have to hit the "Load more..." button to see the related comments).

So presumably the HTML spec is the right venue to raise this in, instead.

Other related concepts to improve performance by deferring _rendering_ of content may include the (albeit discontinued) [`<virtual-scroller>`](https://github.com/WICG/virtual-scroller), and CSS [`content-visibility`](https://drafts.csswg.org/css-contain-2/#content-visibility) (more info https://web.dev/content-visibility/).

**Comment by ayumi-cloud** [comment]
> So presumably the HTML spec is the right venue to raise this in, instead.

I wasn't sure whether to open this here or in `whatwg` that's why I opened and closed this issue at the beginning - will open it over there.

**Comment by gregwhitworth** [comment]
@ayumi-cloud one thing that you can utilize Open UI for is possibly to get feedback from folks on how often libraries lazy load content within components and what type of components they do this on. This will also help bolster the usecases but yes ultimately the work for spec text belongs in WHATWG. Closing this issue out but please re-open it if something changes.
