### ISSUE TITLE
Focus and openui-file

### ISSUE THREAD

**Issue by mrmckeb** [WICG/open-ui#248]
In #140, we've identified that the File input contains a button and label.

When in focus, browsers currently focus the entire component (button and label). The below example is from Chrome:
![image](https://user-images.githubusercontent.com/5043083/104638311-af489580-56ae-11eb-9a72-6122b2926852.png)

Is this something we want to change for `openui-file`? Is there any value in focusing on the inner button as opposed to the input itself?

**Comment by gregwhitworth** [comment]
Removing this from the agenda as I remembered that we already discussed this. Here is the issue that this is a dupe of: https://github.com/WICG/open-ui/issues/107
