### ISSUE TITLE
Should Link have a definition proposal or a full proposal?

### ISSUE THREAD

**Issue by khmakoto** [WICG/open-ui#257]
An issue was recently raised in #253 about whether the `Link` component should have only a definition proposal instead of a full proposal given the limited utilization it has across component libraries. This issue is made to keep track of further development on this as well as to serve as a forum for discussion on the matter.

**Comment by una** [comment]
I'd like to understand where `Link` needs defined anatomy beyond what exists with the `<a>` tag? My initial reaction is that we might not need a proposal for the definition of `Link`.

**Comment by una** [comment]
Resolved at OpenUI: Link will not have separate Research/Definition
