### ISSUE TITLE
Horizontal labels added to this repository

### ISSUE THREAD

**Issue by plehegar** [WICG/open-ui#260]
I added the [horizontal labels](https://w3c.github.io/issue-metadata.html) to this repository. I recommend retiring/removing the 'accessibility' label in this repository and use 'a11y-tracker' instead. The Group can add the label to any issue to automatically bring the discussion to the [attention of the Accessibility Group](https://www.w3.org/PM/horizontal/?repo=w3c/a11y-review) (APA)  Group.

**Comment by gregwhitworth** [comment]
Thanks @plehegar done.
