### ISSUE TITLE
Badges vs. Pills vs. Chips vs. Tags

### ISSUE THREAD

**Issue by una** [WICG/open-ui#266]
The [Badges](http://open-ui.org/components/badge.research) research contains badge components and a "pills" section (as well as "icon"). There is also a [PR](https://github.com/WICG/open-ui/pull/262) open to add Pills research.

I'd like to resolve on:

1. The difference between these components (if any)
2. Clear naming categories

**Comment by una** [comment]
Resolution: https://www.w3.org/2021/03/04-openui-minutes.html#r01

**Comment by gregwhitworth** [comment]
Here is the resolution:

RESOLUTION: Badges and Tags are unique in their semantic usage, we will define the differences
RESOLUTION: Chips and Pills are style-based naming conventions, these will fall under Tags

**Comment by yinonov** [comment]
Does _badges_ have any semantics at all?
_Tags_ can be part of multi selection. Guess there are at least 2 semantic roles that apply
