### ISSUE TITLE
Option elements with icons

### ISSUE THREAD

**Issue by alejsanc** [WICG/open-ui#277]
It would be useful if &lt;option&gt; elements could have an icon in front of the text.

```
Example:

<option icon="/icons/save.svg">Save</option>
```

**Comment by gregwhitworth** [comment]
@alejsanc thanks for filing this. The new spec for `<select>` only prohibits focusable items within an `<option>`, which is a deviation from the current specification for an `<option>` element. This has historical reasons to it working in this way. Given that this new specification enables arbitrary content you actually would be able to do this:

`<option><img src="/icons/save.svg"> Save</option>`

It actually will enable more complex dropdowns as well (imagine a contact list with name, title, avatar, etc inside of grid layout. The only limitations are listed [here](https://open-ui.org/components/select#content-not-allowed-within-the-anatomy)
