### ISSUE TITLE
namespace for project-specific stuff

### ISSUE THREAD

**Issue by nuxodin** [WICG/open-ui#298]
I think it would make sense, as a recommendation, if we "reserved" a namespace for project-specific, private things.

But this would also be useful for Custom Elements, Custom Variables and HTML classes, events and so on.

Using the namespace "p" would look like this:

```css
--p-color:green
```
```html
<p-box>
```
```html
<div class="p-large">
```
```js
addEventListener('p-close')
```

If I understand it correctly, the "data attribute" is somehow designed like this.
https://html.spec.whatwg.org/multipage/dom.html#attr-data-*.

## Naming
"p" is my favorite namespace because it is small and can be associated with "project" and "private"

## Advantages
No one would use this namespace for their own framework.  
This would help when looking at foreign code to see what is project specific or framework dependent.  
You would have a defacto standard that does not need to be further discussed in a team. 

## Background
I got this idea because I am engaged in the topic of web-namespaces.
https://github.com/nuxodin/web-namespace-registry

Close this issue if it does not belong here.

**Comment by gregwhitworth** [comment]
I don't think this ask is a job for Open UI. Open UI may desire to use such functionality, and we do have an `oui` "namespace" for our components but Open UI wouldn't define this API. Ultimately this should be opened on WHATWG but I'd start first with the Web Components group here: https://github.com/WICG/webcomponents

Once it's filed I recommend dropping the issue into discord so other Open UI members can weigh in on their opinions of such a solution.
