### ISSUE TITLE
Thoughts on an incremental approach to <select>/<input> + <datalist>

### ISSUE THREAD

**Issue by domenic** [WICG/open-ui#3]
As we know from @gregwhitworth's [survey](https://www.gwhitworth.com/blog/2019/07/form-controls-components/), `<select>` is the control developers most re-create.

@mfreed7 did some [initial analysis](https://docs.google.com/document/d/1Xa_k_MKfw4QnqHjjOKUW0HWGvgHmZeo7YWWCxTjKWBI/edit) on the stylability of `<select>`. The results are encouraging: at least in some browser/OS combinations, select/option/optgroup are pretty stylable. In particular, in the best case (Windows 10 Chrome):

- Select: sizing, fonts, background, borders stylable
- Option/optgroup: fonts, and background colors (not background images) are stylable
- Also worth mentioning: you can hide the dropdown arrow using `appearance: none`, then make it reappear with `background` tricks. 

Mason linked to [this Filament Group post](https://www.filamentgroup.com/lab/select-css.html) by @scottjehl for more detail.

This inspired me to write up a potential plan for incrementally evolving `<select>`. Here's a rough outline.

### Increase the CSS properties that can be used

Make a list of all CSS properties that could reasonably apply to select/option/optgroup. Be generous: this should include more than just what's possible today, but most things that we think could be reasonable. (E.g. padding, margin, maybe background-image on option...)

Write down this list in a spec. Get cross-browser agreement. Write web platform tests, if possible. Getting this to take off cross-browser is important; web developers need to be able to depend on their selects working as expected everywhere.

(Note: we'd probably have an exception for "popup" implementations of select, as are often seen on mobile platforms. Or watches! My impression is that web developers are OK with such popups not being stylable.)

### Align datalist and select

Web developers often wish that the platform had a "combobox". Good news: it does! [input + datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) gives you a free-form text field with possible suggestions.

However, currently most datalist implementations do not look as aligned with select as they should. Ideally, web developers should get the same look, and same stylability, with input + datalist as they do with select. The only difference should be behavior. They should feel like slight variations on the same control (as they often are on native platforms).

I'm not sure how much spec/tests work we can do here, besides maybe adding some "should" sentences to the spec. This would largely be about getting browsers to agree to converge on a predictable behavior so that web developers come to trust input + datalist.

### Make small, targeted extensions

There are probably many small tweaks we could make to select, and to input + datalist, that would make it more pleasant to style. For example:

- A pseudo-element like `::dropdown-button` (or `::marker`?) to allow developers to replace or style only the dropdown arrow, without having to replace or style the whole control.
- Better support for the notion of a "placeholder option". [The spec seems to have this, sort of](https://html.spec.whatwg.org/multipage/form-elements.html#placeholder-label-option), but only if the `<select>` is `required=""`, and it doesn't impact stylability, only form validation. Maybe we should just make `placeholder=""` work on `<select>`?
- A pseudo-class for when the select is "open".
- A pseudo-class (?) for determining whether the select will "pop up" (like on mobile) or be a dropdown (like on desktop).

These are all off the top of my head, and it would be better to get actual web developer feedback for prioritizing them or generating better ideas.

### Consider UX fixes

Browsers should experiment with just upgrading the user experience of select.

For example, a very common desired experience is that similar to something like [select2](https://select2.org/dropdown), where typing narrows the list of options shown, using substring matching. Note that this experience is already possible using input + datalist, except that input + datalist does not constrain the result to be one of the options; the options there are just suggestions, not the only possible choices. (This suggest another alternative could be something like `<input type=text list=somedatalist constrained>`, instead of modifying `<select>`?)

If we can get agreement on certain user experiences, then maybe we can try to suggest them in the spec, or in general get browsers to align around them, in order to increase web developer confidence that by using select/input + datalist, they are giving their users a good experience.

---

So that's one path. I think it needs to be contrasted with the obvious alternative, of creating a new replacement for `<select>`/`<input>` + `<datalist>` from scratch. Call such a replacement `<superselect>`.

The advantage of the incremental approach is that it's simpler and delivers value incrementally. However, it does have the following disadvantages:

- Developers will forever have to know about both `<select>` and `<input>` + `<datalist>` as two different ways of accomplishing very similar patterns. This is as opposed to just learning about the new `<superselect>`, and ignoring the previous patterns.
- A new `<superselect>` would give us a clean slate, which could be easier for browsers to align around, instead of trying to get everyone to change their long-standing controls.
- A new `<superselect>` gives us the opportunity to introduce more advanced features that can't be added incrementally, such as server-driven autocomplete, arbitrary HTML inside the options, etc.

**Comment by gregwhitworth** [comment]
First - thanks a TON for this analysis. One thing that I'd love is for this to get converted into a markdown file and placed here if possible, at minimum link to it from there: https://github.com/WICG/form-controls-components/blob/master/select/overview.md

> The advantage of the incremental approach is that it's simpler and delivers value incrementally.

I completely agree with doing aspects of these things incrementally and something that I think we'll need to take case-by-case. Technically, there is nothing from us agreeing that all `<select>` elements have a icon of some form and thus deserve an agreed upon sub-part of either `::marker` or other psuedo element name. That then would be likewise included in a `<superselect>` or similar.

>* A new <superselect> would give us a clean slate, which could be easier for browsers to align around, instead of trying to get everyone to change their long-standing controls.
> * A new <superselect> gives us the opportunity to introduce more advanced features that can't be added incrementally, such as server-driven autocomplete, arbitrary HTML inside the options, etc.

These two reasons encapsulate why I think we have to have `<superselect>` or similar as our north star. Because even if `<superselect>` isn't complete we'll unlock many other platform APIs, that on their own will be beneficial to webdevs (eg: top layer, direction position, etc). But yes, all of that adds to the time investment not only from a development perspective but standards as well.

**Comment by mfreed7** [comment]
Nice write-up @domenic! I just wanted to add that I updated the styleability survey document to include <input + datalist>.

**Comment by gregwhitworth** [comment]
I think there is general agreement that we should do an incremental approach to additive features to the web platform as well as try and bring consistency.
