### ISSUE TITLE
[MENU ITEM] Research and discuss / define mouse click behavior of menu items

### ISSUE THREAD

**Issue by nicholasrice** [WICG/open-ui#41]
I wanted to track this since it came up today - there was a question of whether a (context) menu-item should invoke the default action on right-click and I was unable to find any documentation defining the behavior, but many examples of divergent behavior across web and native UIs.

Would be great to tackle this question when we investigate menus and menu items.

**Comment by gregwhitworth** [comment]
Putting this on the backlog unless you want to tackle this sooner. If that is the case please feel free to re-open.
