### ISSUE TITLE
Names section of component pages should be anchors

### ISSUE THREAD

**Issue by nicholasrice** [WICG/open-ui#43]
Under the "Names" section of of each component page (eg. https://open-ui.org/components/button) we list the name of the Design System but we don't link to the resource. I believe we *have* this information because each component entry in a design system is required to have a URL. 

I think we should add anchors to the design system names, linking them to the information resource. Directly linking to the resource brings more transparency about where the information is coming from and allows site users and authors to investigate the design system further if desired.

**Comment by levithomason** [comment]
👍 Shipped

![image](https://user-images.githubusercontent.com/5067638/76125033-cdcf0200-5fb0-11ea-95be-c30af8ce75e3.png)
