### ISSUE TITLE
Naming the button component - small / large - fails the test of time.

### ISSUE THREAD

**Issue by marakoss** [WICG/open-ui#47]
Please let's step aside from what mainstream frameworks do and not name (not just) our buttons small or large.

In your design system your buttons should have unified sizes - if possible. But consider this. You will make a large button for your website - it will be probably used once - in your "carousel" as Call to Action button. Then a new display devices will become available/most used, or new design style will became popular and what do you do? Add new button called "Larger"?

The names shouldn't ever represent how the components looks (eg. small, red, rounded, spaced), but how it behaves (active, disabled) or how its used in your project (standard - primary, icon, ...)

The main point is: If you design a small/large button, a guarantee you that somebody will come and design even smaller/larger button and you won't have a name for it. Don't fall for the same trap as Bootstrap did with grid naming xs, sm, md, lg.

**Comment by levithomason** [comment]
I could be mistaken, but I'm not sure this applies to Open UI at present.  Open UI is not a design system or component library and therefore does not create names or terminology.

Currently, it is a research and documentation effort.  Very similar to how a linguistics and dictionaries document the evolution of language.  They look to reputable sources for new words and new usages of words, then document what the apparent meaning is.  Like Wikipedia, we do not publish original content but instead link to source material (like design systems and component libraries).

This will likely lead us to "bless" or "propose" a direction to be followed form these sources, but for now we are strictly documenting what exists objectively in the UI community.

>The names shouldn't ever represent how the components looks (eg. small, red, rounded, spaced), but how it behaves (active, disabled) or how its used in your project (standard - primary, icon, ...)

Agreed, note the [Naming Principles](https://open-ui.org/) section of our **Vision** :)

>**Names should be void of design information**
>
>**Why?** When designs change names should not become invalid. Names should stand the test of time. Usually, names based on intent or usage are more robust and stand this test. Consider a component that displays mock content while waiting for the actual content to load. It might be more ideally named Placeholder opposed to Shimmer, even though most implementations appears to flash or shimmer. When the design changes and these components no longer shimmer, the name will become invalid and not make sense.

Please feel free to reopen if I've misunderstood the goal here and we can discuss further.

**Comment by marakoss** [comment]
@levithomason 
I just worry that if your centralised overview will show that many of design systems uses this naming, more will perceive this as a way to go.
So it maybe deserve a notice or a flag in a component page (e.g. https://open-ui.org/components/button) that this might not be the best naming that has been developed.
Thank you for response
