### ISSUE TITLE
[MISC] How to handle and define stale documents

### ISSUE THREAD

**Issue by gregwhitworth** [WICG/open-ui#57]
Each group within the W3C has a different way in which to handle stale documents. As we discuss finalizing on the overall process and template I think it's important that the components/controls that we put in place to initially show what Open UI could be should be removed if they aren't actively being worked on. This, similar to other groups, will allow framework/platforms to not look at button, for example, and assume it has made it through the W3C/Open UI standardization process.

I recommend that we remove any document that isn't actively being worked on. I'm open to ideas of possibly adding a toggle or new section that denotes that these are in the Research Phase only.

**Comment by chrisdholt** [comment]
I would agree with this - perhaps we can add badging here as well to denote things which are draft v. recommendation, etc?
