### ISSUE TITLE
Page title element missing from the Open UI website

### ISSUE THREAD

**Issue by d2s** [WICG/open-ui#61]
`<head>` section of the HTML documents on the [open-ui.org](https://open-ui.org/) website lacks `<title>` element.

Even while [seo.js](https://github.com/WICG/open-ui/blob/61e9ffe77953125eea5e83010698a563abcda288/research/src/components/seo.js#L17) component has a `title={title}` in it,
for some reason it _does not_ get rendered to the HTML output.

```jsx
        return (
          <Helmet
            htmlAttributes={{
              lang,
            }}
            title={title}  // NOTE: this element is missing
````
In any case, rest of the sites feels fast & usable. 👍

**Comment by gregwhitworth** [comment]
This is done, thanks for filing
