### ISSUE TITLE
rating suggestion; use <meter>

### ISSUE THREAD

**Issue by tomByrer** [WICG/open-ui#65]
IIRC in the Google Dev talk a star-rating component was flashed on the screen.  But you already have a rating system:
`<meter>` = measurement, just as rating = another type of measure
Thought of this when I saw #55 .

I like the idea of adding more feature-rich components, but seems people can only hold so many APIs / HTML tags in their heads.  EG everything is a `<div>`, when some should be a `<p> <article> <section>` etc...

Perhaps 1 or 2 things could be added to make it more rating friendly, but seems you have most of what you need?  Just the CSS needs to be more standardized, & Edge repeats differently....

Demo: https://codepen.io/tomByrer/pen/RwPddRN
Though it renders differently in localhost:

![rating-meter](https://user-images.githubusercontent.com/1308419/78159093-b3e5db00-7407-11ea-979e-2a3beb929188.png)

**Comment by gregwhitworth** [comment]
@tomByrer Not entirely sure regarding Google proposing a <rating> element. But yes, meter could be researched to see if there are additional parts that could be leveraged to possibly create such a solution. Additionally, and this is important that while Open UI will inform the web platform - it will not be the only components that are covered. All you have to do is look at any framework/design system and you'll see that they have numerous more components that don't exist in the web platform. I don't think it is wrong to have an agreement on across frameworks/design systems on a rating component. The HTML Platform would then, to your point, may/may not introduce a rating element but may augment the <meter> element with new sub parts using part times derived from the rating component.

That said, I can't speak to that until the research is done and an actual proposal for any of the above options is put forth. 100% of my focus currently is on the `<select>`.

For now I'm going to close this thread as there isn't a formal proposal for an HTML element for ratings. If you'd like to investigate the <meter> element and relative specimens across web frameworks, design systems please feel free.
