### ISSUE TITLE
[MISC] We need a better design for the anatomy

### ISSUE THREAD

**Issue by gregwhitworth** [WICG/open-ui#75]
Hey everyone,

I really like the wireframes for showing the component's anatomy, but as we get into some more complex components it gets quite ugly. I'd love if someone that is a good designer could help adjust this a little. Here is the currently defined `<select>` anatomy: https://open-ui.org/components/select#anatomy

![image](https://user-images.githubusercontent.com/865244/79797394-02520f80-830c-11ea-9d12-f54fc6935edb.png)

Some ideas I've been thinking about:

* Be able to show/hide slots
* Come up with a different color scheme
* If an element contains a slot then just add it to the name (eg: button [slot])

Any other ideas are welcome.

**Comment by ststimac** [comment]
Are the current colors indicative of anything in particular? For example, is there a reason button and listbox and option are all green? Is there a reason behind that?

**Comment by gregwhitworth** [comment]
@ststimac yeah - which I actually just caught a bug as <optgroup> should be the same color as listbox and button. But a slot is that yellow color where as parts of a component are that green, and teal is the host element.

**Comment by gregwhitworth** [comment]
Fixed the color bug on `optgroup` which makes it look even more like I'm trying to hypnotize you

**Comment by melanierichards** [comment]
What about a monochromatic color scheme? Pick one color for the host element, lighter and lighter shades of that color for smaller and smaller parts of the component (or the inverse if you prefer). The outlines could also be a very dark shade of that color, maybe with some alpha channel fun thrown in. Slots could have a special treatment, like a dashed line.

**Comment by melanierichards** [comment]
And then maybe additional special treatments based on state, like an accent color and/or double-wide border for selected elements.

**Comment by jakob-e** [comment]
If it can serve as inspiration... https://codepen.io/jakob-e/pen/mderYWm

**Comment by ststimac** [comment]
I like @melanierichards's suggestion to add in some additional treatments with the different borders. Could the slots have a different border treatment as well to help break things out a bit more so we're not just relying on color?

**Comment by gregwhitworth** [comment]
Made the updates. I tried a few different border styles that are built into UAs and unfortunately all of them look ugly besides dash. I used that on the slots which looks good. I leveraged a lot of the code from Jakob so thank you.
