### ISSUE TITLE
Can Flutter framework be included?

### ISSUE THREAD

**Issue by roman-petrov** [WICG/open-ui#78]
Currently Flutter framework also has Web support and good UI component system. Maybe it would be good to include it into https://open-ui.org/analysis/component-matrix?

**Comment by gregwhitworth** [comment]
Hey Roman, we're always willing to have more component libraries added for research. You can learn more about how to add one here if you'd like: https://open-ui.org/contribute. Let me know if you have any questions, as I'm happy to help.
