### ISSUE TITLE
Contribution process is unclear

### ISSUE THREAD

**Issue by matthewp** [WICG/open-ui#79]
The [contributing page](https://open-ui.org/contribute) explains how to document new components but it's not clear to me the exact steps. Should I start documenting a component without first gauging interest with an issue? It seems like that could be a waste of time if there is no interest in that component type.

I would expect a process to go something like:

1. Create an issue about a type of component worth bringing into open ui.
1. If there is interest, start doing research and create a PR.
1. Work on a proposal and a second PR?

The charter page is a little better about explaining the process but it's still a bit unclear to me. https://open-ui.org/charter

**Comment by gregwhitworth** [comment]
Thanks - @matthewp, I'll start writing something up in PR for your review.

**Comment by gregwhitworth** [comment]
Opened a PR to try and address this: https://github.com/WICG/open-ui/pull/84
