### ISSUE TITLE
Slotting custom content into controls using new element types vs built-in <slot>s

### ISSUE THREAD

**Issue by dandclark** [WICG/open-ui#80]
The [Editor's draft for `<select>`](https://open-ui.org/components/select) includes an [anatomy](https://open-ui.org/components/select#anatomy) breaking the control down into distinct parts and slots where a page author could swap in their own HTML to customize the control.

As currently written, the page author would use the `<button>` and new `<listbox>` element to slot their custom content into the `<select>`, e.g.
```html
<select>
    <button>My custom button with custom styles</button>
    <listbox> <!-- potentially styled by the page author -->
        <option>option 1</option>
        <option>option 2</option>
    </listbox>
</select>
```

I'd like to consider an alternative approach where the `<select>` parts are replaced by referencing named `<slot>`s.  For example:
```html
<select>
    <div slot="select-button">My custom button with custom styles</div>
    <div slot="select-listbox"> <!-- potentially styled by the page author -->
        <option>option 1</option>
        <option>option 2</option>
    </div>
</select>
```

Advantages to using elements like `<button>` and `<listbox>` for customizing control UI parts:
* Potentially more intuitive for developers.  With built-in elements it's obvious that the author is doing something standard, whereas this might not be so clear with named `<slot>`s.
* No concerns with `<slot>` name collisions.  I'm not sure how much of a real concern this is though, since the scope of the `<slot>` names is only under a given `<select>` element.

Advantages to using `<slot>`:
* Path to standardization and implementation is shorter without the need to introduce new element types (or update behavior for existing elements like `<button>`).
* There's already well-defined support for fallback content in `<slot>`s for handling cases where the page author wants to replace some parts of the control but not others.  This could be more complex with the new element approach, particularly if we would be relying on parser fixup to fill in elements not supplied by the page author.
* More scalable as we roll this out to more control types.  E.g. for `<input type="slider"/>` it could be easier to standardize more named slots versus introducing `<thumb>`/`<slider>` elements, etc.

I've fleshed out this idea further and provided more examples at https://jsfiddle.net/dandclark_msft/f8vmk6np/2/.

Thoughts?

**Comment by matthewp** [comment]
Can you explain this point?

>  and implementation is shorter without the need to introduce new element types (or update behavior for existing elements like <button>)

What new behavior is needed for button here?

**Comment by dandclark** [comment]
> What new behavior is needed for button here?

When writing that I was thinking about parser behavior that would need to be updated to allow `<button>` under `<select>`,  But, we'd still have to make those sorts of changes for the `<slot>` approach since current parser rules reject just about anything that isn't an `<option>` or `<optgroup>`.  So upon further reflection this is really only an issue with adding new element types.

**Comment by dandclark** [comment]
Another potential issue with the `<button>`/`<listbox>` approach is that there's some ambiguity in determining which slots are filled.

The diagram at https://open-ui.org/components/select shows slots both inside and outside the `<button>` (and `<listbox>`, and `<option>`...).
So with the following markup, does the content go into the slot outside of the button and replace the button itself, or does it inject the "My custom button" text in the slot inside the button and leave the default button in place?
```html
<select>
<button>My custom button contents</button>
</select>
```
I would assume that it is the former case, but then how does one reference the slot inside the button?

This sort of issue could become still more problematic with more complex controls.  Using named `<slot>`s removes this sort of ambiguity.

**Comment by gregwhitworth** [comment]
> This sort of issue could become still more problematic with more complex controls. Using named <slot>s removes this sort of ambiguity.

This is what I'd expect the solution to be. Unfortunately, most of the other component libraries don't have more slot names from what I've seen. @levithomason @chrisdholt @nicholasrice do you all have any thoughts here?
