### ISSUE TITLE
Data structure to describe components

### ISSUE THREAD

**Issue by janechu** [WICG/open-ui#85]
# Background

UI components should have a data structure that describes them. This can be useful for multiple reasons, here are a select few:

- Interpretation by editing UI such as VS Code
- Creation of UI through form field generation
- Validation of data against them
- Used to search through a library of components

Things that should be included in the data structure are:

- Version
- Categories
- Properties/Attributes
- Style/Theming
- Available nesting patterns
- Descriptors

## Proposed structure

```javascript
{
    id: "open-ui-button",
    description: "A button definition",
    version: 1,
    categories: [
        "form"
    ],
    tags: [
        {
            name: "open-ui-button",
            type: "web-component",
            description: "An Open UI button",
            attributes: [
                {
                    name: "disabled",
                    type: "boolean",
                    description: "The disabled state",
                    default: "false",
                    required: false
                }
            ],
            slots: [
                {
                    name: "",
                    description: "The default slot, content in this slot displays directly inside the button"
                }
            ],
            cssProperties: {
                "--my-button-color": "#FF0000",
                "--my-button-font-face": "Arial"
            }
        }
    ]
}
```

I'm using some native HTML web component ideas here, but I think we can extend off of it. What might be some of the design system theory we can add to this?

**Comment by rafegoldberg** [comment]
(I know [vue-styleguidist](https://github.com/vue-styleguidist/vue-styleguidist) has in-built ways of interpreting slot data and merging it with other JSDoc comments meta. Literally no idea what the internals or schema look like, but it definitely might be a good place to look for inspiration.)

**Comment by gregwhitworth** [comment]
@janechu Is the main desire for this to be leveraged by others? We have schema's elsewhere to reference others so I wouldn't be opposed to doing this assuming there are people that want to consume it. Additionally, Open UI does not get into defining styles of the parts so that wouldn't be included if we did this.

**Comment by brianespinosa** [comment]
This reminds me a lot of Semantic UI React's shorthand API. cc @levithomason

**Comment by janechu** [comment]
@rafegoldberg I think there are some commonalities there, and with other JS libraries.

@gregwhitworth Yes, I think what would be ideal is a data structure that can describe as much of a component as possible so that other component libraries can do the same and then there could be shared utilities built around it to re-interpret those structures for various purposes (such as generating UI of the described properties for editing, VS Code plugins etc.). As I mentioned what I've put up is a web component specific look at how a component might be defined, it could be abstracted further.

As for the style bit, I'd like to have an optional way to define some styling concepts for components if there is something like CSS variables which affect the component. It's not necessary for Open UI specifically but other component libraries.

**Comment by janechu** [comment]
Closing in favor of #121 as this has more of the current JSON definitions included.
