### ISSUE TITLE
Inconsistent classification of <select> attributes/methods/properties

### ISSUE THREAD

**Issue by dandclark** [WICG/open-ui#86]
At https://open-ui.org/components/select some states are listed as both attributes and as methods of `<select>`,   Examples are  `autofocus`, `disabled`, and `form`.  All of these should be either one or the other.

The same page also has separate tables for `<option>` attributes and `<option>` properties.  It doesn't seem to me like this is a useful distinction to make in this context.  Would it be clearer to just enumerate the properties (aka IDL attributes)?  Or is there value in accounting for the content attributes separately?

**Comment by gregwhitworth** [comment]
I agree with your statements, feel free to submit a PR to clean that up
