### ISSUE TITLE
Please review switch anatomy and part proposal

### ISSUE THREAD

**Issue by gregwhitworth** [WICG/open-ui#9]
Hey folks,

@domenic and @tkent-google have been working on creating a new built in component of a [toggle switch](https://github.com/tkent-google/std-switch/issues/7#event-2631227687). The open-ui research has done some initial investigations into [Switch](https://open-ui.org/components/switch) and I think it would be valuable to utilize this to begin flushing out what both sides (research & platform) can learn from one another.

**My ask:**
* @levithomason Can you please have the design system folks review the proposal, is there anything that you feel should be added that isn't currently seen in the proposal that you feel conflicts with the data you've gathered
* @domenic @tkent-google is there anything that is within the switch research above that can be clarified and improved for future component designs to speed up the process of part definitions and use cases. The layout and information on that page is in very early stages so any feedback you can provide is valuable.

**Comment by emplums** [comment]
@gregwhitworth is the proposal linked somewhere where we can view it or is the proposal you're referring to the first linked GitHub issue?

**Comment by gregwhitworth** [comment]
@emplums it's here: https://github.com/tkent-google/std-switch/issues/7#event-2631227687 (I linked it above but it is kind of buried 😊)

**Comment by gregwhitworth** [comment]
I've had this open long enough for folks to review it. I'm going to close it for now.
