### ISSUE TITLE
Checkbox State Indicators

### ISSUE THREAD

**Issue by nicholasrice** [WICG/open-ui#93]
Contextual PR discussion: https://github.com/WICG/open-ui/pull/54#discussion_r411660381

Creating an issue to discuss the merits of two different approaches to surfacing state indicators for Checkbox. Checkbox has two distinct state properties:
1. Checked
2. Indeterminate

These two states are independent and are in many default UA implementations hierarchical in that a _checked_ appearance is typically not represented when the element is also _indeterminate_. Note that a given visual design _could_ differentiate all four possible state combinations.

### Two indicators
https://github.com/WICG/open-ui/pull/54 defines two separate elements w/ slots to supply content and CSS to these indicators. Providing two elements facilitates the existing default behavior where the _indeterminate_ appearance  takes precedence over the _checked_ appearance, and allows an app author to easily override the appearance of one state without affecting the other.

### One indicator for both states
https://github.com/WICG/open-ui/pull/54#discussion_r411660381 discusses using only a single element for an indicator. This approach facilitates transitions between states because only a single element is used.

**Comment by gregwhitworth** [comment]
Just an fyi @nicholasrice I tweeted out to get feedback on this
